### ISSUE TITLE
Broken links to the ngsi-browser-widget

### ISSUE THREAD

**Issue by manchandavishal** [wirecloud-fiware/ngsi-browser-widget#3]
There is a broken link in the documentation of the NGSI browser widget when we Click the link FIWARE Lab. It goes to the URL:
https://store.lab.fiware.org/search/keyword/OrionStarterKit
and the content that it is shown is

{"error":"Path not found"}

Currently, I am using the version 2.0.1.

Expected behavior: when we Click the link Fiware Lab it should take us to ngsi-browser-widget in Fiware Store to below URL:
https://store.lab.fiware.org/search/keyword/ngsi-browser-widget.

**Comment by aarranz** [comment]
Hi @manchandavishal,

thanks for your contributions!

The problem here is is that the new link is broken (it is returning an `{"error":"Path not found"}` error) and is not going to work, because we are not updating the instance at store.lab.fiware.org. We are planning to move to use an external catalogue outside FIWARE Lab, but it is going to take some time. Sorry for the inconvenience.

Maybe the solution is to remove the link/text for now or pointing to the releases page at github.

**Comment by manchandavishal** [comment]
Hi @aarranz I have remove the link for Fiware Lab.Please Verify the same.

**Comment by aarranz** [comment]
Sorry for the delay, too much things to do. Thanks for the contribution!
